### ISSUE TITLE
TypeError: a bytes-like object is required, not 'tuple'

### ISSUE THREAD

**Issue by TomBuurmans** [soCzech/TransNetV2#2]
Hi,

I'm attempting to run a test with "python transnetv2.py test.mp4" from the inference folder and getting this error.

```
[TransNetV2] Extracting frames from test.mp4
Traceback (most recent call last):
  File "transnetv2.py", line 192, in <module>
    main()
  File "transnetv2.py", line 172, in main
    model.predict_video(file)
  File "transnetv2.py", line 86, in predict_video
    video = np.frombuffer(video_stream, np.uint8).reshape([-1, 27, 48, 3])
TypeError: a bytes-like object is required, not 'tuple'
```

Not sure where to go from here, let me know if anyone has any ideas.

Cheers

**Comment by TomBuurmans** [comment]
Looks like numpy needed a reinstall, whoops.
