### ISSUE TITLE
training.py can't load models.py

### ISSUE THREAD

**Issue by fschvart** [soCzech/TransNetV2#38]
Hi,

Thank you so much for putting this model out. Excellent work!
I'm trying to train the model and I stumble upon a problem, that points out to the models.py file
When I try to run training.py with the gin file, this is the error message I get:

Traceback (most recent call last):
  File "C:\videoseg\TransNetV2\training\training.py", line 10, in <module>
    import models
  File "C:\videoseg\TransNetV2\training\models.py", line 168, in <module>
    @gin.configurable(blacklist=["name"])
TypeError: configurable() got an unexpected keyword argument 'blacklist'

Do you have a sense of what could be the problem?
Thanks!

**Comment by fschvart** [comment]
OK, found the problem. In latest gin, blacklist has to be replaced with denylist
